"""empty message

Revision ID: 1c7c939406a4
Revises: 
Create Date: 2021-01-24 20:14:26.910865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7c939406a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ikeaitems_tags'), 'ikeaitems', ['tags'], unique=False)
    op.drop_index('ikeaitems_code', table_name='ikeaitems')
    op.drop_index('ikeaitems_tags', table_name='ikeaitems')
    op.drop_index('ikeaitems_url', table_name='ikeaitems')
    op.create_unique_constraint(None, 'ikeaitems', ['url'])
    op.create_unique_constraint(None, 'ikeaitems', ['code'])
    op.create_index(op.f('ix_plikeaitems_tags'), 'plikeaitems', ['tags'], unique=False)
    op.drop_index('plikeaitems_code', table_name='plikeaitems')
    op.drop_index('plikeaitems_tags', table_name='plikeaitems')
    op.create_unique_constraint(None, 'plikeaitems', ['code'])
    op.create_index(op.f('ix_posts_history'), 'posts', ['history'], unique=False)
    op.drop_index('posts_history', table_name='posts')
    op.drop_index('posts_item_id', table_name='posts')
    op.create_unique_constraint(None, 'posts', ['item_id'])
    op.drop_index('tasks_url', table_name='tasks')
    op.create_unique_constraint(None, 'tasks', ['url'])
    op.drop_index('tgusers_tel_id', table_name='tgusers')
    op.create_unique_constraint(None, 'tgusers', ['tel_id'])
    op.create_index(op.f('ix_uaikeaitems_tags'), 'uaikeaitems', ['tags'], unique=False)
    op.drop_index('uaikeaitems_code', table_name='uaikeaitems')
    op.drop_index('uaikeaitems_tags', table_name='uaikeaitems')
    op.create_unique_constraint(None, 'uaikeaitems', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uaikeaitems', type_='unique')
    op.create_index('uaikeaitems_tags', 'uaikeaitems', ['tags'], unique=False)
    op.create_index('uaikeaitems_code', 'uaikeaitems', ['code'], unique=True)
    op.drop_index(op.f('ix_uaikeaitems_tags'), table_name='uaikeaitems')
    op.drop_constraint(None, 'tgusers', type_='unique')
    op.create_index('tgusers_tel_id', 'tgusers', ['tel_id'], unique=True)
    op.drop_constraint(None, 'tasks', type_='unique')
    op.create_index('tasks_url', 'tasks', ['url'], unique=True)
    op.drop_constraint(None, 'posts', type_='unique')
    op.create_index('posts_item_id', 'posts', ['item_id'], unique=True)
    op.create_index('posts_history', 'posts', ['history'], unique=False)
    op.drop_index(op.f('ix_posts_history'), table_name='posts')
    op.drop_constraint(None, 'plikeaitems', type_='unique')
    op.create_index('plikeaitems_tags', 'plikeaitems', ['tags'], unique=False)
    op.create_index('plikeaitems_code', 'plikeaitems', ['code'], unique=True)
    op.drop_index(op.f('ix_plikeaitems_tags'), table_name='plikeaitems')
    op.drop_constraint(None, 'ikeaitems', type_='unique')
    op.drop_constraint(None, 'ikeaitems', type_='unique')
    op.create_index('ikeaitems_url', 'ikeaitems', ['url'], unique=True)
    op.create_index('ikeaitems_tags', 'ikeaitems', ['tags'], unique=False)
    op.create_index('ikeaitems_code', 'ikeaitems', ['code'], unique=True)
    op.drop_index(op.f('ix_ikeaitems_tags'), table_name='ikeaitems')
    # ### end Alembic commands ###
