"""empty message

Revision ID: 401ce2e9e7e5
Revises: 6e85c89a482d
Create Date: 2021-02-02 17:48:10.957879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401ce2e9e7e5'
down_revision = '6e85c89a482d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ikeaproduct', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('ikeaproduct', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('ikeaproduct', 'is_new',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ikeaproduct', 'is_new',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('ikeaproduct', 'updated_at')
    op.drop_column('ikeaproduct', 'created_at')
    # ### end Alembic commands ###
