"""product table fields

Revision ID: 6e85c89a482d
Revises: dbd9c0091bd2
Create Date: 2021-01-25 23:43:41.764781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e85c89a482d'
down_revision = 'dbd9c0091bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ikeaproduct', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('ikeaproduct', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('ikeaproduct', sa.Column('is_new', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ikeaproduct', 'is_new')
    op.drop_column('ikeaproduct', 'is_available')
    op.drop_column('ikeaproduct', 'create_date')
    # ### end Alembic commands ###
