"""data ru pl ua

Revision ID: 9f36279c4638
Revises: fcedb687167f
Create Date: 2021-01-25 00:40:03.325022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f36279c4638'
down_revision = 'fcedb687167f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ikeaproduct', sa.Column('country', sa.String(length=5), nullable=False))
    op.add_column('ikeaproduct', sa.Column('data', sa.JSON(), nullable=True))
    op.add_column('ikeaproduct', sa.Column('pl_data', sa.JSON(), nullable=True))
    op.add_column('ikeaproduct', sa.Column('ru_data', sa.JSON(), nullable=True))
    op.add_column('ikeaproduct', sa.Column('ua_data', sa.JSON(), nullable=True))
    op.drop_constraint('ikeaproduct_code_key', 'ikeaproduct', type_='unique')
    op.drop_column('ikeaproduct', 'raw_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ikeaproduct', sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_unique_constraint('ikeaproduct_code_key', 'ikeaproduct', ['code'])
    op.drop_column('ikeaproduct', 'ua_data')
    op.drop_column('ikeaproduct', 'ru_data')
    op.drop_column('ikeaproduct', 'pl_data')
    op.drop_column('ikeaproduct', 'data')
    op.drop_column('ikeaproduct', 'country')
    # ### end Alembic commands ###
